### ISSUE TITLE
Populate Feature Table

### ISSUE THREAD

**Issue by gzt5142** [gzt5142/nldi-crawler-py#18]
Upon reading the GeoJSON for a feature returned from a source, map it to a `Feature` and insert into the correct table in `nldi-demo` database. 

The GeoJSON parsing is already sorted out using `ijson`. Just need to: 

- [x] Create ORM for feature table
- [x] create the table with tmp name
- [x] Insert all features
- [x] swap tmp with 'real' feature table
- [x] Clean up

**Comment by gzt5142** [comment]
An important consideration for creating features -- the CRS of the data we get from various sources. 

The original java port of this tool set a default CRS as NAD83.  But that doesn't seem to be what we are getting back from all of the sources in the `crawler_source` table. Returned data is in OGC::CRS84 per the [GeoJSON Spec](https://geojson.org/geojson-spec.html#named-crs)... although it is possible to name a CRS explicitly. 

Some sources explicitly state CRS84, others do not declare a CRS at all (so we have to assume CRS84, per the spec). 

I'm not finding any documentation or other help to understand why the java port explicitly creates features in NAD83. I will proceed with WGS84/CRS84 as the spatial reference when inserting features. This may have implications downstream when we do intersection tests and other spatial queries.

**Comment by gzt5142** [comment]
I was disappointed to learn that some of the feature-table properties are postgress specific.  meaning that the benefits of sqlalchemy and geoalchemy are less applicable.

THe java port that I am modeling from uses a shell-game shuffle of table names to achieve updates from a particular source.  the master `feature` table is a parent, with an inheritance relationship with all of the feature tables from all sources. This works fine (I assume), so I will continue with that model.  

A more surgical option would be to update/insert rows to a master `feature` table per feature returned from the source. That would likely be more performant, as data only needs to update if changed. 

Anyway:
```
CREATE tmp_table LIKE feature INCLUDING INDEXES
... populate tmp_table ...
DROP TABLE feature_suffix
ALTER TABLE tmp_table RENAME TO feature_suffix
ALTER TABLE feature_suffice INHERIT feature
```

**Comment by dblodgett-usgs** [comment]
Re the CRS, as long as axis order isn't an issue (which it shouldn't be here) you can safely assume CRS84 is equivalent to NAD83.

**Comment by gzt5142** [comment]
I'm sure struggling with the implementation details related to inserts to the feature table.  The main problem is that the feature table (and its heirs) do not have a primary key defined. Unique identity mapping is proving to be a challenge. 

The solution seems to be to generate a 'fake' primary key as a combination of crawler_source_id and the feature_id of returned data.

**Comment by gzt5142** [comment]
@dblodgett-usgs 
> Re the CRS, as long as axis order isn't an issue (which it shouldn't be here) you can safely assume CRS84 is equivalent to NAD83.

Just to be clear -- CRS84 is equivalent to WGS84 (the only difference being the ordering of the coordinates).  To be completely accurate, a transform should be applied to go from WGS84 to NAD83 and vice-versa. Without a transform, the spatial error is, I think, about a meter or so for continental US locations. 

I take your note above to mean that a meter or so is an acceptable margin for spatial error on this project. I suspect that our source data is not spatially accurate to that level anyway....

**Comment by dblodgett-usgs** [comment]
Yeah - that's what I meant by can be assumed to be the same.

**Comment by gzt5142** [comment]
closing this issue... but there is a related issue to worry about -- linking with nhd catchments/basins. will address under separate cover.
